aaa_standard = "SSP1"
aaa_namespace = "ssd"
aaa_name = "Enums"

[ComponentType]
fmu = {enum = "application/x-fmu-sharedlibrary"}
ssd = {enum = "application/x-ssp-definition"}
ssp = {enum = "application/x-ssp-package"}