aaa_standard = "FMI2"
aaa_namespace = "md"
aaa_name = "Enums"

[Status]
ok = {enum_val = "ok"}
warning = {enum_val = "warning"}
discard = {enum_val = "discard"}
error = {enum_val = "error"}
fatal = {enum_val = "fatal"}

[Causality]
parameter = {enum_val = "parameter"}
calculatedParameter = {enum_val = "calculatedParameter"}
input = {enum_val = "input"}
output = {enum_val = "output"}
local = {enum_val = "local"}
independent = {enum_val = "independent"}

[Variability]
constant = {enum_val = "constant"}
fixed = {enum_val = "fixed"}
tunable = {enum_val = "tunable"}
discrete = {enum_val = "discrete"}
continuous = {enum_val = "continuous"}

[Initial]
exact = {enum_val = "exact"}
approx = {enum_val = "approx"}
calculated = {enum_val = "calculated"}

[DependenciesKind]
dependent = {enum_val = "dependent"}
constant = {enum_val = "constant"}
fixed = {enum_val = "fixed"}
tunable = {enum_val = "tunable"}
discrete = {enum_val = "discrete"}

[LogCategory]
logEvents = {enum_val = "logEvents"}
logSingularLinearSystems = {enum_val = "logSingularLinearSystems"}
logNonlinearSystems = {enum_val = "logNonlinearSystems"}
logDynamicStateSelection = {enum_val = "logDynamicStateSelection"}
logStatusWarning = {enum_val = "logStatusWarning"}
logStatusDiscard = {enum_val = "logStatusDiscard"}
logStatusError = {enum_val = "logStatusError"}
logStatusFatal = {enum_val = "logStatusFatal"}
logStatusPending = {enum_val = "logStatusPending"}
logAll = {enum_val = "logAll"}

[FmiType]
real = {enum_val = "real"}
integer = {enum_val = "integer"}
boolean = {enum_val = "boolean"}
string = {enum_val = "string"}
enumeration = {enum_val = "enumeration"}
